/* This file was generated by r.out.leaflet GRASS GIS module. */

var layerInfos = [
   {title: "mapbox_wdpstrcov_2m.020", file: "mapbox_wdpstrcov_2m.020.png", bounds: [[35.73279068, -78.67497504], [35.73953038, -78.68274044]], opacity: 1.0}
,   {title: "mapbox_wdpstrcov_2m.040", file: "mapbox_wdpstrcov_2m.040.png", bounds: [[35.73279068, -78.67497504], [35.73953038, -78.68274044]], opacity: 1.0}
,   {title: "mapbox_wdpstrcov_2m.060", file: "mapbox_wdpstrcov_2m.060.png", bounds: [[35.73279068, -78.67497504], [35.73953038, -78.68274044]], opacity: 1.0}
,   {title: "mapbox_wdpstrcov_2m.080", file: "mapbox_wdpstrcov_2m.080.png", bounds: [[35.73279068, -78.67497504], [35.73953038, -78.68274044]], opacity: 1.0}
,   {title: "mapbox_wdpstrcov_2m.100", file: "mapbox_wdpstrcov_2m.100.png", bounds: [[35.73279068, -78.67497504], [35.73953038, -78.68274044]], opacity: 1.0}
,   {title: "mapbox_wdpstrcov_2m.120", file: "mapbox_wdpstrcov_2m.120.png", bounds: [[35.73279068, -78.67497504], [35.73953038, -78.68274044]], opacity: 1.0}
];
